### ISSUE TITLE
Ny template, mobile first

### ISSUE THREAD

**Issue by steinmb** [smbjorklund/dhs#1]
Ny template må være satt for mobil først slik at besøkende med mindre skjermer får en god opplevelse.

**Comment by steinmb** [comment]
Akkurat nå tester jeg ut 3 forskjellige jeg har laget. De bor i hver sine brancher i git

- https://github.com/smbjorklund/dhs/tree/7.x-1.x Zen basert
- https://github.com/smbjorklund/dhs/tree/7.x-2.x Omega 4 og libSass basert. Veldig bleeding edge.
- https://github.com/smbjorklund/dhs/tree/7.x-3.x Omega 4 og Compass basert linjen.

**Comment by hewiro** [comment]
Har kanskje ikke noen betydning, men ser du har lagt til en "first sidebar"(?) Vi bruker vel kun "second sidebar" for DHS?

**Comment by steinmb** [comment]
"First" er den første man bruker. Spiller ingen rolle om den ligger på høyre eller venstre side. Det var grunnen til at man sluttet å bruke betegnelsen venstre og høyre -sidebar.

**Comment by steinmb** [comment]
Nå ser sidene mere ut som et arbeidsområde. Har slått på DHS sitt ikke fullt ferdige theme.

**Comment by steinmb** [comment]
Den nye templaten er mobilklar (first) og vi kan begynne å teste på mobiltelefoner, tablet, fablet osv. De blokkene du brukte/har på Bartik theme må bli slått på i DHS. Du kan bare aktivere de du trenger der.

**Comment by hewiro** [comment]
Hahh...ser jo rent lekkert ut på mobilen. Har testet dette og ser at det fungerer som du sa, men hvordan blir det når karusellen blir lagt til? Blir den borte? 
På min gamle lille telefon dekker siden hele skjermen og vel så det, slik at de første bokstaver på hver linje i venstre bildekant er halvert. Tester nettbrettet i kveld...

**Comment by hewiro** [comment]
Main page content - blokka er lagret under "Content" men viser ikke på siden. Inneholder denne blokka den samme som Main menu? Om ikke, hva er forskjellen?

**Comment by steinmb** [comment]
>Main page content - blokka er lagret under "Content" men viser ikke på siden. Inneholder denne blokka den samme som Main menu? Om ikke, hva er forskjellen?

"Main page content" er hvor Drupal spytter ut noder og sånt. Du kan ved å flytte den bestemme hvilken region i templaten man ønsker at de skal vises.

"Main menu" er bare en meny. Lages av Drupal som standard og man velge å bruke den eller bare ignorere den. Finner den på /admin/structure/menu/manage/main-menu/edit. Blokkmodulen til drupal muliggjør at menyer og kan danne blokker som man kan flytte rundt. Har men en nettside der man ikke har bruk for blokker forblir meny bare menyer og ikke noe annet.

**Comment by steinmb** [comment]
>Hahh...ser jo rent lekkert ut på mobilen. Har testet dette og ser at det fungerer som du sa, men hvordan blir det når karusellen blir lagt til? Blir den borte? 
På min gamle lille telefon dekker siden hele skjermen og vel så det, slik at de første bokstaver på hver linje i venstre bildekant er halvert. Tester nettbrettet i kveld...

Har opprettet en egen sak vi kan teste små skjermer på #9
