### ISSUE TITLE
Fotoalbum

### ISSUE THREAD

**Issue by steinmb** [smbjorklund/dhs#12]
Generell sak om fotoalbumet.

* [x] Droppe sidebar når man viser fotoalbum og bilder.
* [x] Grid layout, lignede den i bruk for ansatte.
* [ ] Bla i bildene i fotoalbum
* [ ] Link som gir mulighet til å legge til et bilde i fotoalbum. Vi prepopulerer referanse feltet og resturerer brukeren tilbake etter det er lagt til.

### Drupal 6

![60_talls_huset___de_heibergske_samlinger-sogn_folkemuseum](https://cloud.githubusercontent.com/assets/683617/10642383/b9564d94-781d-11e5-8465-05572bb61859.png)

**Comment by hewiro** [comment]
Vi har manglet "bla i bildene" i albumene. Ser og at bildene i D7 vil ligge under hverandre i stedet for slik de viser her... Er det slik de vil vise publisert?

**Comment by steinmb** [comment]
Som du ser har vikke enda begynt å jobbe på den

Typed with my thumbs

**Comment by hewiro** [comment]
Veldig greit å bruke samme Grid for disse og, silk som i "Tilsette". Fint med en lik visning som en visuell helhet på siden.

**Comment by steinmb** [comment]
Har gjort en del oppdateringer:

86c593a Added  tablet image layout method.
7de6fdd Allow gallery layouts to use <ul> as lists.
126fe65 Photo gallery and ansatte should now keep to correct grid.
bafac06 Doh, forgot to set content div on non node based pages.
68ed7d6 Gems update used by Susy
6f7fae6 Image gallery and Susy grids debugging in all breakpoints.
47a4487 Fjerer breadcrumb
b47f72b Flytter tittel naar vi lister bilder i node teaser mode.

**Comment by steinmb** [comment]
Stopper her. Splitter de to som gjenstår inn i separate saker. Lar ikke denne være en megasak som skal ordne alt, blir for rot da:

6411e8d Tagger i artikkler og bilder plasseres horisontalt.
59335a6 Foto album improvments.
98b2b42 Center title and border around pictures in fotoalbum list.
0846bf1 Reduce size of image title in teaser mode.
02085e0 Bugfix - Do not write ansatt title when in teaser view mode.

## Follow up issues
*  Bla i bildene i fotoalbum #22 
*  Link som gir mulighet til å legge til et bilde i fotoalbum. #23
