### ISSUE TITLE
Ordered lists skal ikke ha bullets

### ISSUE THREAD

**Issue by steinmb** [smbjorklund/dhs#14]
Order lister får nå bullets. Dette bør vi nok ikke ha. 
Eksempel artikkel har vi på: http://dhs.smbjorklund.no/audioguide

    <ol>
       <li> Dett er en ordered liste </li>
    </ol>

![audioguide___de_heibergske_samlinger-sogn_folkemuseum_and_dhs_norsk](https://cloud.githubusercontent.com/assets/683617/10602501/f6ab9bf0-7718-11e5-93d2-300b7f9d3f96.png)

## Etter fix

![the_open-air_museum___de_heibergske_samlinger-sogn_folkemuseum_and_dhs_styles_scss_-_drupal-7_-____sites_dhs_migration_take2_drupal-7__-_phpstorm_ps-143_279](https://cloud.githubusercontent.com/assets/683617/10638579/fe20e842-780b-11e5-811d-87c3e9419092.png)

## Hvordan teste
Gå til http://dhs.smbjorklund.no/audioguide og eller opprett en sånn list i en artikkel og test at de ikke har disse røde firkantene.

**Comment by hewiro** [comment]
Fjernet listen og la inn på nytt, men de røde firkantene er der fortsatt....

**Comment by hewiro** [comment]
Har også laget en ny artikkel der resultatet er det samme. http://dhs.smbjorklund.no/node/5224

**Comment by steinmb** [comment]
Dette er en feil i CSS, ikke noe for deg.

**Comment by steinmb** [comment]
Skal være ordnet med 49211c1
