### ISSUE TITLE
Redusere menypunkter og manelt arbeid med å vedlikeholde disse

### ISSUE THREAD

**Issue by steinmb** [smbjorklund/dhs#15]
@hewiro La oss konsentrere arbeidet rudt forenkling av menyer og sånt. Større ting splitter vi bare ut i separate saker sånn at vi kan lukke noen av disse.

## Arbeidsomfang
* [x] Utstillinger - http://dhs.smbjorklund.no/utstillingar
* [x] Tenester - http://dhs.smbjorklund.no/tenester
* [x] Om museet - http://dhs.smbjorklund.no/node/5183
* [x] Husk å fjerne linjen “ Meir om utstillingane kan du lesa her…’ fra http://dhs.smbjorklund.no/utstillingar
* [x] Tagge innhold med korrekte tagger.
* [x] Fjerne http://dhs.smbjorklund.no/utstillingane
* [ ] Fjerne tagger fra disse hovesidene som vi nå tar i bruk. De trenger ikke tagger.

### Historie
>@steinmb Denne siden: http://dhs.smbjorklund.no/arkiv Føler at i stedet for at du trenger å opprette manuelle lenker til de burde vi heller lage en view som plukker ut alle slike artikkler. Kansje kan vi bruke en avtalt tagg på disse sån får vi autmagisk en list - f.eks emneordet “artikkel” for å skille disse ut?

>@hewiro Helt enig i det med view, en god måte å løse dette på. Artikkel er en grei tagg for dette...
Er trolig tilbake på "normal" uke fra mandag.  

>@hewiro Har sett på Arkiv nå og dette er en grei måte å løse det på. God oversikt og alfabetisk rekkefølge. Trenger ikke thumbs her for å illustrere innholdet.

>@steinmb Tilbake til disse view/blokkene. Kan vi gjøre samme opprydding på f.eks http://dhs.smbjorklund.no/utstillingane
Føler at de er akkurat samme saken som den arkivsaken. Disse blokkene er og gjenbrukbare på andre sider.

>@hewiro Joda, det kan vi. Det forenkler jo redigeringen og tar mindre plass i menyene...

**Comment by steinmb** [comment]
La oss starte med ustillinger http://dhs.smbjorklund.no/utstillingane. hvilken tagg skal vi bruke på de for sortering?

**Comment by hewiro** [comment]
Kan vi bare bruke "Utstillingar"?

**Comment by steinmb** [comment]
Har lagt til en blokk som bruker taggen "utstillingar". Bare å tagge innhold nå.

**Comment by steinmb** [comment]
Flytter saken over på deg, tror ikke jeg har så mye mere jobb her. Du har noe tagger å fjerne å noen å legge til. Forslår f.eks at de hovedsidene vi nå tar i bruk ikke har noen taksomoni tagger.

**Comment by hewiro** [comment]
Nå har jeg tagget, tegget og tugget på alt innhold, artikler og bilder på norsk og engelsk. Tror ikke det er mer vi kan gjør med dette nå...
