### ISSUE TITLE
flytte tittel under bilde på node typer som trenger dette i hennhold til design

### ISSUE THREAD

**Issue by steinmb** [smbjorklund/dhs#16]
Dette i henhold til gjeldene design.

* Artikkeltype: Innhold

![the_open-air_museum___de_heibergske_samlinger-sogn_folkemuseum_-__private_browsing_](https://cloud.githubusercontent.com/assets/683617/10602870/394d9c0e-771b-11e5-9caa-c2eaa0573ed2.png)

**Comment by hewiro** [comment]
Liker at tittelen ligger under bildet. Ser ryddigere ut(?)

**Comment by steinmb** [comment]
Commit 2dc91c0d6c62b2f9fdbb460bebc8d9ae04f78e7b endrer dette på artikkler. Skal se om vi trenger det på andre. Trolig foto.... sjekker

**Comment by steinmb** [comment]
Commit 0350b49 endrer dette for innholdstypen bilde.

**Comment by steinmb** [comment]
Anser meg som ferdig. Ta en kikk om alt er OK.
