### ISSUE TITLE
Style breadcrumb

### ISSUE THREAD

**Issue by steinmb** [smbjorklund/dhs#18]
Finnes ingen styling for denne:

## Nåværende utseende
![museumsgarden___de_heibergske_samlinger-sogn_folkemuseum](https://cloud.githubusercontent.com/assets/683617/10637874/3ddb6088-7808-11e5-9199-d4ea29df85c1.png)

**Comment by hewiro** [comment]
Ser at den røde firkanten ar borte dersom det er det du mener. Det var den som laget krøll i systemet for noen dager siden "bug". Om jeg ikke husker feil er den firkanten en del av designet. Lager det krøll om den er med her på menyene?

**Comment by steinmb** [comment]
Nei ikke det. Brødsmulestien har vi nå i bruk. På Drupal 6 er den av. Enten må den bort eller så må den få et bedre utsseende. Vanligvis bruker vi de bare når man har dype nettsteder med mye innhold som navigasjonshjelp

Typed with my thumbs

**Comment by steinmb** [comment]
Forslår av vi bare fjernet denne. Vi bruker den ikke på D6.

**Comment by steinmb** [comment]
Commit 47a4487 fjernet denne fra templaten vår.
