### ISSUE TITLE
Rydde bort harde linjeskift in artikkler

### ISSUE THREAD

**Issue by steinmb** [smbjorklund/dhs#20]
Fjerne hard linjeskift som ødelegger linje og leseflyt i artikkler.

- Video i dropbox linjeskift.mp4 som beskriver problemet.

**Comment by hewiro** [comment]
Her er jeg helt på høyde. Flere slike artikler står på "Må gjøre" listen min, men godt å bli minnet på det. Vil og fjerne CC koden. Den ble lagt inn etter krav fra en forfatter av en artikkel som stod i en gammel årbok. Vi er nå kommet til enighet om at artikler fra årbøker er museet sine egne og kan brukes fritt.

**Comment by hewiro** [comment]
Skal ikke bare skylde på kopiering fra Words her ser jeg, Har nok syndet litt i redigeringen etter innliming, men noen ganger blir det noe rusk i lenketeksten ved ÆØÅ som her ved å: <a href="http://dhs.smbjorklund.no/%C3%A5rbok/%C3%A5rbok-sogn-2010">Meir om innhaldet</a>
Har det noen betydning om det står slik? Hva skjer om jeg retter dette i lenkene?

**Comment by steinmb** [comment]
Rettet kommentaren din over. Om du setter linjer med kode alene og med 4 mellom først som jeg her gjorde så blir den vist som kode og ikke forsøkt rendered som html.

Aah, den god gamle æøå i URL addressser. I utgangspunktet kan man bruke norske tegn i addresser men det er ikke trygt. Ikke alle nettlesere forstår det. Dermed styrer de fleste unna.

### Exempel fra NRK
    http://www.nrk.no/norge/advarer-mot-a-skille-vapen-og-ammunisjon-1.12635148
    http://www.nrk.no/hordaland/emil-_11_-var-forste-pasient-pa-den-nye-legevakten-1.12636357

Hær skriver de å om til bokstaven a og ø til o.
Hvordan disse alias blir laget kan man endre når artikkelen blir opprettet eller manuelt etterpå.

Ved å gjøre det omgår man at spesialtegn blir omskrevet som du har i ditt eksempel:

    http://dhs.smbjorklund.no/%C3%A5rbok/%C3%A5rbok-sogn-2010

å blir skrevet om til %C3%A5
Om nettleseren forstår å i addressen blir den da automagisk krevet om til dette, kan den det ikke det, blir den stående som den er.

**Comment by steinmb** [comment]
Har laget deg en egen oppgave for alias jobb. Prøv å holde oppgavene fra hverandre.
" Rydde og forbedre alias-regler og redirect #21 "
