### ISSUE TITLE
Lurer på ting og tang

### ISSUE THREAD

**Issue by steinmb** [smbjorklund/dhs#4]
Hvorfor kommer menytittel og lenker som er opprettet under en meny frem på oversiden av oversikten over menyer, blokker og stort sett alle andre steder der de ikke skal være – se f.eks. menyer?

Innholdet i «body» er plassert (formatert) annerledes i D7 enn i D6. Kan dette redigeres i D7 uten at systemet endrer det tilbake ved neste migrasjon?

Hva gjør vi med de fire feltene på fremsiden? Blir det som før, at vi må ha innholdet på begge språk for at nodekøen skal virke? Dette må vi unngå. Det blir for tungvint. Må prøve å skille norsk og engelsk side, også tysk når den kommer.

**Comment by steinmb** [comment]
>Hva gjør vi med de fire feltene på fremsiden? Blir det som før, at vi må ha innholdet på begge språk for at nodekøen skal virke? Dette må vi unngå. Det blir for tungvint. Må prøve å skille norsk og engelsk side, også tysk når den kommer.

@hewiro  Nei dette blir ikke som før. Vi kommer ikke til å lenger bruke nodekø-modulen.

**Comment by steinmb** [comment]
>Innholdet i «body» er plassert (formatert) annerledes i D7 enn i D6. Kan dette redigeres i D7 uten at systemet endrer det tilbake ved neste migrasjon?

Dette forstår jeg ikke helt. Plassert anderledes? Når du viser artikkelen eller når du redigerer den? Har du en addresse til en sånn?

**Comment by steinmb** [comment]
>Hvorfor kommer menytittel og lenker som er opprettet under en meny frem på oversiden av oversikten over menyer, blokker og stort sett alle andre steder der de ikke skal være – se f.eks. menyer?

@hewiro Ikke helt sikker på om jeg følger deg her. Vær klar over at blokker følger utseendemalen. Dvs. det er et oppsett for diss for hver template f.eks http://dhs.smbjorklund.no/admin/structure/block/list/seven

<img width="1067" alt="blocks___de_heibergske_samlinger-sogn_folkemuseum" src="https://cloud.githubusercontent.com/assets/683617/9196490/1d852f3a-402c-11e5-86d8-8c987ca29bdb.png">

**Comment by hewiro** [comment]
![opningstider](https://cloud.githubusercontent.com/assets/10771091/9218333/ceef20c8-40d1-11e5-846c-2dd95f72469c.JPG)
Her er det jeg ikke forstod. Jeg har opprettet/plassert alle nye blokker/menyer i Bartik. Blir litt usikker når ting skjer som jeg ikke helt forstår med en gang, som f.eks. at nytt innhold blir lagret flere ganger: 
![lagring av innhold](https://cloud.githubusercontent.com/assets/10771091/9218684/b81a6ae4-40d4-11e5-8722-cd7a76882b35.JPG)


Forskjellen i formateringen fra D6 til D7 ser du her i D6: http://dhs.museum.no/%C3%A5rbok-sogn
Og i D7: http://dhs.smbjorklund.no/%C3%A5rbok-sogn

Endringen jeg gjorde i D7 i går ser ut til å holde, selv etter nattens migrasjon... Bekymrer meg trolig for mye over ting jeg ikke forstår med en gang...

**Comment by hewiro** [comment]
Får ikke bytte bilder i artiklene, så det får jeg vente med. Vil ikke gjøre slike endringer i D6. Kan legge inn bilder i artikler der det ikke er fra før, men når jeg prøver å bytte får jeg denne meldingen:
![feilmelding ved redigering av innhold i d7](https://cloud.githubusercontent.com/assets/10771091/9221833/78eca742-40ed-11e5-95fb-5f5e6c4d6ea5.JPG)

**Comment by steinmb** [comment]
>Forskjellen i formateringen fra D6 til D7 ser du her i D6: http://dhs.museum.no/%C3%A5rbok-sogn
Og i D7: http://dhs.smbjorklund.no/%C3%A5rbok-sogn

Ikke tenk på formateringer enda. Vi må først få på plass vårt eget theme før vi trenger å se på sånne ting. Så lenge HTML som er migrert fra Drupal 6 er identisk i Drupal 7 så har vi alt vi trenger.

**Comment by hewiro** [comment]
Okidoki....

**Comment by hewiro** [comment]
Hei
Kikker litt rundt på innholdstypene og på "Innhold", og på "Foto" står det "Rendered file". Hva betyr det i dette tilfellet? Render har mange meninger, men er usikker på hva det betyr i forbindelse med data. Hva skjer dersom jeg f.eks. endrer størrelsen på bildene? Kanskje det er for tidlig/om nødvendig å gjøre slike grep, men jeg er bare nysgjerrig (klør litt og).

**Comment by steinmb** [comment]
Render-fanen kommer fra devel modulen. Den gir oss muligheten til å se rådata av en node slik den er etter den er kjørt gjennom utseendemalen (rendered). Den fanen "loaded" er hva den inneholder når den blir lastet direkte fra databasen, aka før den blir rendered.

Ikke tenk på størrelsene av bildene. Vi mekker på dem etterpå når vi bytter til vår eget theme.

**Comment by hewiro** [comment]
Har det noe for seg å legge inn en editor på dette tidspunkt?
Har prøvd å endre URL-er som ligger som lenker i tekst, men uten hell. Mye arbeid uten editor. 

Noterer dette her slik at jeg husker dette når vi kommer over i vårt theme. Lett å glemme.

**Comment by hewiro** [comment]
Under et lite møte i dag er det sett frem et sterkt ønske om en tysk variant av hjemmesiden. Det er gjort en avtale med ei som skal oversette innholdet til den tyske siden. Hun er tysk og har vært guide her på museet i flere år.
Vi må ta dette med i beregningen og aktivere tysk som språkvalg...

**Comment by steinmb** [comment]
>Har det noe for seg å legge inn en editor på dette tidspunkt?
Har prøvd å endre URL-er som ligger som lenker i tekst, men uten hell. Mye arbeid uten editor.

Har du en node som du sliter med slik at jeg kan se på dette?

**Comment by hewiro** [comment]
Fant en løsning på problemet ved å endre adressen inne i URL-en, fra dhs.museum.no til dhs.smbjorklund.no
Dette gjelder da kun de interne lenkene, ikke de eksterne. De funka fint...

**Comment by hewiro** [comment]
Kan jeg endre tittelen «Ansatte» til «Tilsette» i View-et uten at noe galt skjer?

**Comment by steinmb** [comment]
>Fant en løsning på problemet ved å endre adressen inne i URL-en, fra dhs.museum.no til dhs.smbjorklund.no
Dette gjelder da kun de interne lenkene, ikke de eksterne. De funka fint...

Pls. ikke bruk slike lenker. Hvor er du driver å lager disse?

**Comment by hewiro** [comment]
Dette er lenker som fører tilbake til DHS i D6, selv om de er migrert over i D7. 
Her er en lenke etter endringen i D7: http://dhs.smbjorklund.no/glav%C3%A6rstova

**Comment by steinmb** [comment]
eeh, noe forvirret nå. Den Drupal 7 noden inneholder ingen lenke, heller ikke den orginale Drupal 6 noden, http://dhs.museum.no/node/72. Så hvor er det du lager disse lenkene?

**Comment by hewiro** [comment]
Sorry, feil lenke. På siden http://dhs.smbjorklund.no/sogn-fjordmuseum-kaupanger ligger en lenke som skal føre til artikkelen om Glaværstova. Denne lenken førte tilbake til DHS i D6. Endret i lenken i redigeringsmodus (edit) og da fant lenken siden som er migrert. 
Tror ikke det har skjedd noe katastrofalt for alt fungerer normalt for disse lenkene jeg har endret...

**Comment by hewiro** [comment]
Glemte å si at det finnes et eksempel på dette problemet på samme siden, den som viser til bygging av Sognafæringen. Denne har jeg ikke endret...

**Comment by steinmb** [comment]
>Sorry, feil lenke. På siden http://dhs.smbjorklund.no/sogn-fjordmuseum-kaupanger ligger en lenke som skal føre til artikkelen om Glaværstova. Denne lenken førte tilbake til DHS i D6. Endret i lenken i redigeringsmodus (edit) og da fant lenken siden som er migrert. 

Ah. Dette er bare forvirring mellom relativ og absolutte hyperlinker. Om man ønsker kan man bruke relative lenker når man peker til eget innhold. Da spiller det ingen rolle hvilket domene som nettsidene kjører på. Her har du et ekspempel:

### Absolut lenke
    <a href="http://dhs.smbjorklund.no/glaværstova" target="_self">Glaværstova</a>

### Relativ lenke
     <a href="/glaværstova" target="_self">Glaværstova</a>

**Comment by hewiro** [comment]
![sprak](https://cloud.githubusercontent.com/assets/10771091/9715530/7583ae2e-5561-11e5-965c-be33cb74280f.JPG)
Skjer det noe galt om jeg endrer Bokmål til Norsk her?

**Comment by hewiro** [comment]
Driver systemet og migrerer ennå? Skulle gjerne slettet det engelske kartet som viser hvordan man finner museet, og lage en ny oversettelse slik at denne siden blir lik norsk og tysk. 

Engelsk: http://dhs.smbjorklund.no/en/our-location
Norsk: http://dhs.smbjorklund.no/her-finn-du-oss
Tysk: http://dhs.smbjorklund.no/de/node/5201

Har ikke endret aliaset på den tyske ennå, da jeg er litt usikker på oversettelsen. Venter litt med det...

**Comment by steinmb** [comment]
>Driver systemet og migrerer ennå? 

Hei. Har gått over til at vi migrerer når vi trenger det.

**Comment by steinmb** [comment]
>Skjer det noe galt om jeg endrer Bokmål til Norsk her?

Har du URL til hvor du vil endre dette?

**Comment by hewiro** [comment]
Er så snarest innom DHS i D7 i dag og lurer på et par ting. 

1.	Når legger du ut det riktige designet/tema?
2.	Om vi ser på f.eks. menyen «Arkiv» http://dhs.smbjorklund.no/arkiv under «Publikasjoner», så har jeg lagt til noen undermenyer med diverse artikler. 
http://dhs.smbjorklund.no/admin/structure/menu/manage/menu-publikasjonar 

Disse artiklene kommer ikke frem uten at jeg haker av for   "Show as expanded". Haker jeg av her er undermenyene åpne konstant. Tar jeg bort haken kommer de altså ikke frem i det hele tatt. 

Dette problemet er kun under «Publikasjonar» og jeg har trolig sett meg litt blind på det hele for jeg greier ikke se hva jeg har gjort forskjellig på denne og de andre menyene. 
Har et svakt minne om at jeg har vært borte i dette for noen år siden også, kanskje med en annen hjemmeside, men husker ikke hva/hvordan dette ble løst.

**Comment by steinmb** [comment]
Hei Helge

Jobber på menyer og selve forsiden i dag og i morgen. Selve menyene. Ikke bruk tid på å tenke på det med exanded eller ikke. La de bare stå som de er, det kommer til nok å være greit så lenge de er undermenyer. Mangler bare noe CSS (og kansje noe js for telefoner) for at det skal legges ut korrekt.

Denne siden:
http://dhs.smbjorklund.no/arkiv

Føler at i stedet for at du trenger å opprette manuelle lenker til de burde vi heller lage en view som plukker ut alle slike artikkler. Kansje kan vi bruke en avtalt tagg på disse sån får vi autmagisk en list - f.eks emneordet “artikkel” for å skille disse ut?

**Comment by hewiro** [comment]
Helt enig i det med view, en god måte å løse dette på. Artikkel er en grei tagg for dette...
Er trolig tilbake på "normal" uke fra mandag.

**Comment by steinmb** [comment]
Mekker til et view da så får vi se om det fungerer greit

Typed with my thumbs

**Comment by steinmb** [comment]
Hei. Vet ikke om du var innom http://dhs.smbjorklund.no/arkiv og kikka på den. Kommenter gjerne hva som er greit og hva vi treng å endre.

**Comment by hewiro** [comment]
Har sett på Arkiv nå og dette er en grei måte å løse det på. God oversikt og alfabetisk rekkefølge. Trenger ikke thumbs her for å illustrere innholdet, men under "Fotoalbum" er jeg litt usikker. Hadde kanskje sett litt mer fristende ut å se flere bilder dersom det låg et forran albumtittel. Kanskje ikke så lett all den tid det er et view som plukker dette opp? Er som sagt usikker, så det kan vi se nærmere på når vi har publisert. Det gjelder også en del andre ting som vi kanskje ser noe bedre da. 

Har fått mange nye bilder på bordet som jeg vil gjøre klart til bruk og blant annet til karusellen. Blir den lik som før? Har brukt størrelse 944 x 351 på disse...de passer akkurat i karusellen...

**Comment by steinmb** [comment]
Foreslår at vi holder oss til disse blokken til vi er helt ferdig med de. Målsettingen er å fjerne alle de unødvendige manelle operasjone for vedlikehold av sidene framover. Tipper vi og kommer til å utrydde mange meny punkter.

* Fotoalbumet kan du bare kopiere og lime inn i #12
* Forside karusell samler vi på #13

**Comment by steinmb** [comment]
Tilbake til disse view/blokkene. Kan vi gjøre samme opprydding på f.eks http://dhs.smbjorklund.no/utstillingane
Føler at de er akkurat samme saken som den arkivsaken. Disse blokkene er og gjenbrukbare på andre sider.

**Comment by hewiro** [comment]
Joda, det kan vi. Det forenkler jo redigeringen og tar mindre plass i menyene...

**Comment by steinmb** [comment]
Lukker denne. Tror vi ikke trenger denne mere.
