### ISSUE TITLE
Aktivere tysk språk

### ISSUE THREAD

**Issue by steinmb** [smbjorklund/dhs#5]
Sidene kommer til å få Tysk språk og vi bør slå på støtte for artikkler i dette språket og.

**Comment by steinmb** [comment]
Jeg har slått på Tysk. Var greit å gjøre det da jeg og fant et rettighetsprobem i filesystemet som gjorde at vi ikke fikk nedlastet nye oversettelser av Drupal og ekstramoduler.

**Comment by hewiro** [comment]
Flott
Tror jeg har fått redigert det som er mulig av de norske sidene nå og vil starte med de engelske. 
Ved oversetting av menyer legger disse seg som egne menyfaner sammen med de norske i hovedmenyen. Det blir altså både norske og engelske menyer samtidig. Hvordan skille menyene fra den ene siden til den andre? Blir vel samme med tysk...

**Comment by hewiro** [comment]
Har fått spørsmål om det er mulig å bruke flagg i stedet for tekst på språkvalgene. Er det vanskelig å få til?

**Comment by steinmb** [comment]
>Har fått spørsmål om det er mulig å bruke flagg i stedet for tekst på språkvalgene. Er det vanskelig å få til?
Nei men må sjekke om det er regler rundt dette for disse nettsidene. Vi kan ikke bare fjerne teksten. Da vil blinde og svaksynte som bruker skjermlesere kunne navigere siden da bare ikoner ikke gir noe informasjon om hva for lenker dette egentlig er.

**Comment by hewiro** [comment]
Høres både riktig og fornuftig ut. Vi gjør det som på gamlesiden, da er vi i alle fall sikker...

**Comment by steinmb** [comment]
Må i allefall holde oss innenfor WACAG 2.0 standarden.
http://www.w3.org/TR/WCAG20/

**Comment by hewiro** [comment]
Skal vi ha et eget felt for tyske "tags"?
Min tysk er elendig, men jeg har en som vil gi meg en liste over tyske "tags" ut fra de vi har på norsk og engelsk dersom vi trenger det..

**Comment by steinmb** [comment]
>Skal vi ha et eget felt for tyske "tags"?

La meg tenke litt på det. Er litt opptatt i dag med ELMCIP.

**Comment by steinmb** [comment]
Har laget #10 slik at vi ikke glemmer av dette

**Comment by steinmb** [comment]
Testet i dag og anser oss som ferdige til nå. Innhold på tysk kommer etterhvert
