### ISSUE TITLE
Marger for innhold i sidebar mangler

### ISSUE THREAD

**Issue by steinmb** [smbjorklund/dhs#7]
<img width="510" alt="de_heibergske_samlinger-sogn_folkemuseum" src="https://cloud.githubusercontent.com/assets/683617/9576623/a23941be-4fd9-11e5-887b-d6575788a3e8.png">

**Comment by steinmb** [comment]
@hewiro Regner med at jeg finner en løsning på dette ved å kikke på http://susy.oddbird.net. Bør være en støtte for dette uten å manuelt å gjøre et CSS hack.

**Comment by hewiro** [comment]
Som en siste innspurt før avspasering en uke har jeg laget et forslag til fremside. Nå skal jeg være den første til å innrømme at jeg aner ikke hvor mye arbeid dette kan bli for deg å rigge til, men om dette er mulig(?) så vil vi kunne få mye mer informasjon ut på fremsiden...i alle fall i forhold til i dag. Er innom nettet inn i mellom selv om jeg ikke er på jobb, ellers holder vi kontakten på telefonen...
![ny framside-side 001](https://cloud.githubusercontent.com/assets/10771091/10304328/b9651e24-6c19-11e5-992d-d823e01a93c5.jpg)

**Comment by steinmb** [comment]
Denne saken er nå i orden.
