### ISSUE TITLE
Lage liste over tilsette

### ISSUE THREAD

**Issue by steinmb** [smbjorklund/dhs#8]
Vi har en egen innholdstype som lagrer:
- Stilling
- Epost
- Telefon
- Stillingsbeskrivelse

Vi har en view list lister ut de ansatte på http://dhs.smbjorklund.no/tilsette (var http://dhs.smbjorklund.no/ansatte).

**Comment by steinmb** [comment]
@hewiro Endret tittel men også path til listen fra http://dhs.smbjorklund.no/ansatte til http://dhs.smbjorklund.no/tilsette

**Comment by steinmb** [comment]
På de listene. Kan du ikke heller legge inn vanlige rektangulære ansattbilder? Portrait orjentert. Om vi trenger de sirkulære osv bør vi la dette gjøres av CSS i templaten vår.

**Comment by hewiro** [comment]
Jo det er meningen at bildene skal være firkantet, men siden folk er så trege med å levere bilder har jeg bare lagt til noen foreløpige bilder for å se hvordan dette fungerte. Skal presse på litt for å få gode passbilder av de som ikke har levert og skifte de ut. Kan se ut til at noen vegrer seg for å ha bildet sitt på siden, så de får bare være svarte så lenge...

**Comment by steinmb** [comment]
Commit: 4903121feb078ead0af901dc4cb6495d56d75ebe
Har lagt en demovideo i dropboxen vår: Ansattliste.mp4

**Comment by steinmb** [comment]
### Iphone 4Gs iOS9 Safari
![img_1277](https://cloud.githubusercontent.com/assets/683617/10309396/9cd8f474-6c3c-11e5-9dc1-c78a716b6093.jpg)
En eller annen bug som gjør at vi ikke fyller ut bredden.

**Comment by hewiro** [comment]
Dette blir altså min nye hobby når jeg går av neste år...hmmm
Min tlf fyller bredden og vel så det, spesielt teksten går litt ut forbi i venstre marg - både på tlf og nettbrettet.

**Comment by steinmb** [comment]
Det samme på iPhone 5 og iOS 9. 4 tommers skjerm 640×1136 pixels at 326 ppi.

**Comment by steinmb** [comment]
Ah, testet litt mere. Det ser ut som det er når vi overskriver minimum bredde. Dette vil skje med eldre og mindre skjermer som gir deg ned mot 400px og mindre horisontalt. Holder man telefonen horisontalt er det greit. I stedet for 320 x 480px får man da 480 x 320px.

**Comment by hewiro** [comment]
Hadde du lagt en ny video i Dropboxen? Om ansatte? Den er ikke kommet til min box...

**Comment by steinmb** [comment]
Hmmm, skal ta en kikk

**Comment by steinmb** [comment]
Lukker denne. Resten fortsetter i " Formatering av ansatte siden #11 "
